name: Build APK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Buildozer
        run: |
          sudo apt update
          sudo apt install -y zip unzip build-essential libffi-dev
          pip install --upgrade cython==0.29.37
          pip install --upgrade buildozer

      - name: Construir APK
        run: buildozer android debug

      - name: Descargar APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-Listo
          path: bin/
          *.apk
