name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev
          pip install --upgrade cython==0.29.36
          pip install --upgrade git+https://github.com/kivy/buildozer.git
          pip install --upgrade git+https://github.com/kivy/python-for-android.git

      - name: Clean old build
        run: |
          rm -rf.buildozer
          mkdir -p ~/.android/licenses
          printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c1059b8ea4b6ca\n" > ~/.android/licenses/android-sdk-license
          mkdir -p ~/.android && touch ~/.android/repositories.cfg

      - name: Force install build-tools 34
        run: |
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p $ANDROIDSDK/cmdline-tools
          cd $ANDROIDSDK/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip -q tools.zip
          mkdir -p latest
          mv cmdline-tools/* latest/ || true
          rm -rf cmdline-tools tools.zip
          export PATH=$ANDROIDSDK/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;34.0.0" "platform-tools"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: osi-cheker-apk
          path: bin/*.apk
